repo_url: https://github.com/Sachin1801/Personal_Portfolio
title: Sachin Adlakha | Portfolio
description: >-
  I'm a Computer Science graduate student at New York University, specializing in developing trading platforms and AI solutions. 
  With experience in quantitative analysis and full-stack development, I've built projects ranging from automated trading systems 
  to computer vision applications. Currently seeking Summer 2025 internship opportunities in Software Engineering and Quantitative roles.

og:
  title: Sachin Adlakha's Portfolio
  image_height: 1440
  image_width: 1080
  image_url: https://ksaitarun.com/assets/profile.jpg

cta:
  primary: Hire Me!

social:
  name_initials: SA
  full_name: Sachin Adlakha
  short_name: Sachin
  email: sachinadlakha1801@gmail.com
  facebook: https://www.facebook.com/sachin.adlakha.7
  github: https://github.com/Sachin1801
  # google_play: https://play.google.com/store/apps/dev?id=6017027472682723980
  # instagram: https://www.instagram.com/saitarunkaniganti
  linkedin: https://www.linkedin.com/in/sachin-adlakha/
  medium: https://medium.com/@sachinadlakha7
  twitter_id: sachinadlakha18
  twitter_url: https://x.com/sachinadlakha18
  # youtube: https://www.youtube.com/c/SaiTarunKaniganti

theme_color: "#77cbd4"
baseurl: "" # repo name, leave blank for user/org pages.
url: "https://ksaitarun.com" # Full URL, always.

permalink: /:title

defaults:
  - scope:
      path: ""
    values:
      layout: default

sass:
  style: :compressed

# These won't matter for drop-in HTML replacements
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap

exclude:
  - LICENSE
  - README.md

